### ISSUE TITLE
Load elements

### ISSUE THREAD

**Issue by AfroEuro** [PatrickShaw/monorepo#1]

**Comment by PatrickShaw** [comment]
Hi @AfroEuro just confirming: Was opening this issue an accident?

It appears you've created an issue without a description

**Comment by AfroEuro** [comment]
Ok i wanted to ask about how to make my elements be seen eth

**Comment by PatrickShaw** [comment]
Still fairly confused as to what this issue is about. I've gone and closed it but feel free to re-open if you have more information to provide about what this is all about.

Thanks!
